import { api } from "@/lib/axios";

type ApiResponse<T> = { data: T; message?: string; success?: boolean };

function unwrap<T>(res: { data: ApiResponse<T> }): ApiResponse<T> {
  return res.data;
}

// Categories
export type Category = { id: string; name: string; slug: string; imageUrl?: string | null; showOnHome?: boolean; homeOrder?: number };

export const categoriesApi = {
  getAll: () => api.get<ApiResponse<Category[]>>("/categories").then(unwrap).then((r) => r.data ?? []),
  create: (name: string, image?: File, showOnHome?: boolean, homeOrder?: number) => {
    const form = new FormData();
    form.append("name", name);
    if (image) form.append("image", image);
    if (showOnHome !== undefined) form.append("showOnHome", String(showOnHome));
    if (homeOrder !== undefined) form.append("homeOrder", String(homeOrder));
    return api.post<ApiResponse<Category>>("/categories", form, { headers: { "Content-Type": "multipart/form-data" } }).then(unwrap);
  },
  update: (id: string, name: string, image?: File, showOnHome?: boolean, homeOrder?: number) => {
    const form = new FormData();
    form.append("name", name);
    if (image) form.append("image", image);
    if (showOnHome !== undefined) form.append("showOnHome", String(showOnHome));
    if (homeOrder !== undefined) form.append("homeOrder", String(homeOrder));
    return api.put<ApiResponse<Category>>(`/categories/${id}`, form, { headers: { "Content-Type": "multipart/form-data" } }).then(unwrap);
  },
  delete: (id: string) => api.delete<ApiResponse<null>>(`/categories/${id}`).then(unwrap),
};

// SubCategories
export type SubCategory = {
  id: string;
  name: string;
  slug: string;
  categoryId: string;
  imageUrl?: string | null;
  category?: { id: string; name: string; slug: string };
};

export const subCategoriesApi = {
  getAll: () =>
    api.get<ApiResponse<SubCategory[]>>("/subcategories").then(unwrap).then((r) => r.data ?? []),
  getByCategory: (categoryId: string) =>
    api.get<ApiResponse<SubCategory[]>>(`/subcategories/category/${categoryId}`).then(unwrap).then((r) => r.data ?? []),
  getByCategories: async (categoryIds: string[]): Promise<SubCategory[]> => {
    if (!categoryIds.length) return [];
    const arrays = await Promise.all(categoryIds.map((id) => subCategoriesApi.getByCategory(id)));
    const seen = new Set<string>();
    return arrays.flat().filter((s) => {
      if (seen.has(s.id)) return false;
      seen.add(s.id);
      return true;
    });
  },
  create: (name: string, categoryId: string, image?: File) => {
    const form = new FormData();
    form.append("name", name);
    form.append("categoryId", categoryId);
    if (image) form.append("image", image);
    return api.post<ApiResponse<SubCategory>>("/subcategories", form, { headers: { "Content-Type": "multipart/form-data" } }).then(unwrap);
  },
  update: (id: string, data: { name?: string; categoryId?: string }, image?: File) => {
    const form = new FormData();
    if (data.name) form.append("name", data.name);
    if (data.categoryId) form.append("categoryId", data.categoryId);
    if (image) form.append("image", image);
    return api.put<ApiResponse<SubCategory>>(`/subcategories/${id}`, form, { headers: { "Content-Type": "multipart/form-data" } }).then(unwrap);
  },
  delete: (id: string) => api.delete<ApiResponse<null>>(`/subcategories/${id}`).then(unwrap),
};

// Products
export type ProductImage = { id: string; url: string; position: number };
export type CategoryRef = { id: string; name: string; slug?: string };
export type SubCategoryRef = { id: string; name: string; slug?: string };
export type ProductFeatureTag = "NEW_ARRIVAL" | "TRENDING" | "BEST_SELLER" | null;
export type ProductStatus = "DRAFT" | "PUBLISHED";
export type Product = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  moq?: string | null;
  specifications?: Record<string, string> | null;
  tradeInfo?: Record<string, string> | null;
  featureTag?: ProductFeatureTag;
  isFeatured?: boolean;
  isNewArrival?: boolean;
  isHighDemand?: boolean;
  showOnHome?: boolean;
  isActive?: boolean;
  status?: ProductStatus;
  createdAt: string;
  images: ProductImage[];
  categories: CategoryRef[];
  subCategories: SubCategoryRef[];
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaKeywords?: string | null;
  ogImage?: string | null;
  seoAutoGenerated?: { metaTitle?: boolean; metaDescription?: boolean; metaKeywords?: boolean; ogImage?: boolean };
};

export const productsApi = {
  getAll: () => api.get<ApiResponse<Product[]>>("/products").then(unwrap).then((r) => r.data ?? []),
  getOne: (slug: string) => api.get<ApiResponse<Product>>(`/products/${slug}`).then(unwrap).then((r) => r.data!),
  getById: (id: string) => api.get<ApiResponse<Product>>(`/products/by-id/${id}`).then(unwrap).then((r) => r.data!),
  create: (data: {
    name: string;
    description?: string;
    moq?: string;
    specifications?: Record<string, string>;
    tradeInfo?: Record<string, string>;
    categoryIds: string[];
    subCategoryIds?: string[];
    metaTitle?: string;
    metaDescription?: string;
    metaKeywords?: string;
    featureTag?: ProductFeatureTag;
    isFeatured?: boolean;
    isNewArrival?: boolean;
    isHighDemand?: boolean;
    showOnHome?: boolean;
    isActive?: boolean;
    status?: ProductStatus;
  }, images?: File[]) => {
    const form = new FormData();
    form.append("name", data.name);
    form.append("description", data.description ?? "");
    if (data.moq) form.append("moq", data.moq);
    if (data.specifications) form.append("specifications", JSON.stringify(data.specifications));
    if (data.tradeInfo) form.append("tradeInfo", JSON.stringify(data.tradeInfo));
    form.append("categoryIds", JSON.stringify(data.categoryIds));
    form.append("subCategoryIds", JSON.stringify(data.subCategoryIds ?? []));
    if (data.metaTitle) form.append("metaTitle", data.metaTitle ?? "");
    if (data.metaDescription) form.append("metaDescription", data.metaDescription ?? "");
    if (data.metaKeywords) form.append("metaKeywords", data.metaKeywords ?? "");
    if (data.featureTag !== undefined && data.featureTag !== null) form.append("featureTag", data.featureTag);
    form.append("isFeatured", String(data.isFeatured ?? false));
    form.append("isNewArrival", String(data.isNewArrival ?? false));
    form.append("isHighDemand", String(data.isHighDemand ?? false));
    form.append("showOnHome", String(data.showOnHome ?? false));
    form.append("isActive", String(data.isActive ?? true));
    form.append("status", data.status ?? "PUBLISHED");
    images?.forEach((f) => form.append("images", f));
    return api.post<ApiResponse<Product>>("/products", form, { headers: { "Content-Type": undefined } }).then(unwrap);
  },
  update: (id: string, data: Partial<{
    name: string;
    description: string;
    moq: string;
    specifications: Record<string, string>;
    tradeInfo: Record<string, string>;
    categoryIds: string[];
    subCategoryIds: string[];
    metaTitle: string;
    metaDescription: string;
    metaKeywords: string;
    featureTag: ProductFeatureTag;
    images: ProductImage[];
    isFeatured: boolean;
    isNewArrival: boolean;
    isHighDemand: boolean;
    showOnHome: boolean;
    isActive: boolean;
    status: ProductStatus;
  }>, images?: File[]) => {
    const form = new FormData();
    form.append("name", data.name ?? "");
    form.append("description", data.description ?? "");
    form.append("moq", data.moq ?? "");
    form.append("specifications", data.specifications ? JSON.stringify(data.specifications) : "");
    form.append("tradeInfo", data.tradeInfo ? JSON.stringify(data.tradeInfo) : "");
    form.append("categoryIds", JSON.stringify(data.categoryIds ?? []));
    form.append("subCategoryIds", JSON.stringify(data.subCategoryIds ?? []));
    form.append("metaTitle", data.metaTitle ?? "");
    form.append("metaDescription", data.metaDescription ?? "");
    form.append("metaKeywords", data.metaKeywords ?? "");
    form.append("isFeatured", String(data.isFeatured ?? false));
    form.append("isNewArrival", String(data.isNewArrival ?? false));
    form.append("isHighDemand", String(data.isHighDemand ?? false));
    form.append("showOnHome", String(data.showOnHome ?? false));
    form.append("isActive", String(data.isActive ?? true));
    form.append("status", data.status ?? "PUBLISHED");
    form.append("existingImages", JSON.stringify(data.images ?? []));
    images?.forEach((f) => form.append("images", f));
    return api.put<ApiResponse<Product>>(`/products/${id}`, form, { headers: { "Content-Type": undefined } }).then(unwrap);
  },
  delete: (id: string) => api.delete<ApiResponse<null>>(`/products/${id}`).then(unwrap),
  deleteImage: (productId: string, imageId: string) => api.delete<ApiResponse<null>>(`/products/${productId}/images/${imageId}`).then(unwrap),
  bulkAssignCategories: (productIds: string[], categoryIds: string[], subCategoryIds?: string[]) =>
    api.post<ApiResponse<{ updated: number }>>("/products/bulk-assign-categories", { productIds, categoryIds, subCategoryIds }).then(unwrap),
};

// Videos
export type Video = {
  id: string;
  title: string;
  description: string | null;
  videoUrl: string;
  videoUrlResolved?: string | null;
  thumbnail?: string | null;
  thumbnailResolved?: string | null;
  section?: string;
  isActive: boolean;
  order: number;
  createdAt: string;
};

export const videosApi = {
  getAll: (section = "1") => api.get<ApiResponse<Video[]>>(`/videos/all?section=${section}`).then(unwrap).then((r) => r.data ?? []),
  getActive: (section = "1") => api.get<ApiResponse<Video[]>>(`/videos?section=${section}`).then(unwrap).then((r) => r.data ?? []),
  create: (data: { title: string; description?: string; isActive?: boolean; order?: number; section?: string }, videoFile: File, onProgress?: (pct: number) => void) => {
    const form = new FormData();
    form.append("video", videoFile);
    form.append("title", data.title);
    if (data.description) form.append("description", data.description);
    if (data.isActive !== undefined) form.append("isActive", String(data.isActive));
    if (data.order !== undefined) form.append("order", String(data.order));
    if (data.section) form.append("section", data.section);
    return api.post<ApiResponse<Video>>("/videos", form, {
      headers: { "Content-Type": undefined },
      onUploadProgress: (e) => {
        if (e.total && onProgress) onProgress(Math.round((e.loaded * 100) / e.total));
      },
    }).then(unwrap);
  },
  update: (id: string, data: { title?: string; description?: string; isActive?: boolean; order?: number; section?: string }, videoFile?: File, onProgress?: (pct: number) => void) => {
    const form = new FormData();
    if (data.title) form.append("title", data.title);
    if (data.description !== undefined) form.append("description", data.description ?? "");
    if (data.isActive !== undefined) form.append("isActive", String(data.isActive));
    if (data.order !== undefined) form.append("order", String(data.order));
    if (data.section) form.append("section", data.section);
    if (videoFile) form.append("video", videoFile);
    return api.put<ApiResponse<Video>>(`/videos/${id}`, form, {
      headers: { "Content-Type": undefined },
      onUploadProgress: (e) => {
        if (e.total && onProgress) onProgress(Math.round((e.loaded * 100) / e.total));
      },
    }).then(unwrap);
  },
  reorder: (orderedIds: string[], section = "1") => api.patch<ApiResponse<Video[]>>("/videos/reorder", { orderedIds, section }).then(unwrap),
  toggleActive: (id: string) => api.patch<ApiResponse<Video>>(`/videos/${id}/toggle-active`).then(unwrap),
  delete: (id: string) => api.delete<ApiResponse<null>>(`/videos/${id}`).then(unwrap),
};

export const fullScreenVideoApi = {
  getAdmin: () => api.get<ApiResponse<Video | null>>("/videos/fullscreen/admin").then(unwrap).then((r) => r.data ?? null),
  getPublic: () => api.get<ApiResponse<Video | null>>("/videos/fullscreen").then(unwrap).then((r) => r.data ?? null),
  save: (data: { title?: string; description?: string; isActive?: boolean }, videoFile?: File, onProgress?: (pct: number) => void) => {
    const form = new FormData();
    if (data.title) form.append("title", data.title);
    if (data.description !== undefined) form.append("description", data.description ?? "");
    if (data.isActive !== undefined) form.append("isActive", String(data.isActive));
    if (videoFile) form.append("video", videoFile);
    return api.post<ApiResponse<Video>>("/videos/fullscreen", form, {
      headers: { "Content-Type": undefined },
      onUploadProgress: (e) => {
        if (e.total && onProgress) onProgress(Math.round((e.loaded * 100) / e.total));
      },
    }).then(unwrap);
  },
  toggleActive: () => api.patch<ApiResponse<Video>>("/videos/fullscreen/toggle-active").then(unwrap),
  delete: () => api.delete<ApiResponse<null>>("/videos/fullscreen").then(unwrap),
};

// Gallery
export type GalleryItem = { id: string; image: string; imageUrl?: string; title: string | null };

export const galleryApi = {
  getAll: () => api.get<ApiResponse<GalleryItem[]>>("/gallery").then(unwrap).then((r) => r.data ?? []),
  upload: (file: File, title?: string) => {
    const form = new FormData();
    form.append("image", file);
    if (title) form.append("title", title);
    return api.post<ApiResponse<GalleryItem>>("/gallery", form, { headers: { "Content-Type": "multipart/form-data" } }).then(unwrap);
  },
  delete: (id: string) => api.delete<ApiResponse<null>>(`/gallery/${id}`).then(unwrap),
};

// Banners
export type Banner = {
  id: string;
  title: string;
  desktopImage: string;
  mobileImage: string;
  desktopImageUrl?: string;
  mobileImageUrl?: string;
  link: string | null;
  isActive: boolean;
  order: number;
  createdAt: string;
};

export const bannersApi = {
  getAll: () => api.get<ApiResponse<Banner[]>>("/banners/all").then(unwrap).then((r) => r.data ?? []),
  getActive: () => api.get<ApiResponse<Banner[]>>("/banners?isActive=true").then(unwrap).then((r) => r.data ?? []),
  create: (form: FormData) => api.post<ApiResponse<Banner>>("/banners", form, { headers: { "Content-Type": "multipart/form-data" } }).then(unwrap),
  update: (id: string, form: FormData) => api.put<ApiResponse<Banner>>(`/banners/${id}`, form, { headers: { "Content-Type": "multipart/form-data" } }).then(unwrap),
  reorder: (orderedIds: string[]) => api.patch<ApiResponse<Banner[]>>("/banners/reorder", { orderedIds }).then(unwrap),
  toggleActive: (id: string) => api.patch<ApiResponse<Banner>>(`/banners/${id}/toggle-active`).then(unwrap),
  delete: (id: string) => api.delete<ApiResponse<null>>(`/banners/${id}`).then(unwrap),
};

// Contact (CRM)
export type InquiryStatus = "PENDING" | "CONTACTED" | "IN_PROGRESS" | "COMPLETED" | "REJECTED";
export type ContactInquiry = {
  id: string;
  name: string;
  phone: string;
  email?: string | null;
  message: string;
  quantity: string | null;
  unit?: string | null;
  productId?: string | null;
  productName?: string | null;
  source?: string | null;
  status: InquiryStatus;
  adminNotes: string | null;
  followUpDate: string | null;
  lastUpdatedById: string | null;
  lastUpdatedBy: { id: string; name: string | null; email: string } | null;
  createdAt: string;
  updatedAt: string;
};

export type ContactInquiriesResponse = {
  data: ContactInquiry[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
};

export const contactApi = {
  getInquiries: (params: { page?: number; limit?: number; search?: string; status?: string; dateFrom?: string; dateTo?: string }) => {
    const sp = new URLSearchParams();
    if (params.page != null) sp.set("page", String(params.page));
    if (params.limit != null) sp.set("limit", String(params.limit));
    if (params.search) sp.set("search", params.search);
    if (params.status) sp.set("status", params.status);
    if (params.dateFrom) sp.set("dateFrom", params.dateFrom);
    if (params.dateTo) sp.set("dateTo", params.dateTo);
    return api.get<ApiResponse<ContactInquiriesResponse>>(`/contact/inquiries?${sp}`).then(unwrap).then((r) => r.data!);
  },
  updateInquiry: (id: string, data: { status?: InquiryStatus; adminNotes?: string | null; followUpDate?: string | null }) =>
    api.patch<ApiResponse<ContactInquiry>>(`/contact/inquiries/${id}`, data).then(unwrap).then((r) => r.data!),
  deleteInquiry: (id: string) => api.delete<ApiResponse<null>>(`/contact/inquiries/${id}`).then(unwrap),
};
