import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import JoditEditor from "jodit-react";
import { categoriesApi, subCategoriesApi, productsApi, type Product, type ProductImage, type ProductFeatureTag } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ImageUploadZone } from "@/components/ImageUploadZone";
import { toast } from "sonner";
import { getApiError } from "@/lib/axios";
import { ChevronDown, ChevronRight } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const JODIT_CONFIG = {
  height: 400,
  minHeight: 400,
  width: "100%",
  toolbar: true,
  toolbarButtonSize: "middle" as const,
  toolbarSticky: false,
  showCharsCounter: true,
  showWordsCounter: true,
  showXPathInStatusbar: false,
  allowResizeX: false,
  allowResizeY: true,
  resizeMinHeight: 400,
  buttons: [
    "source", "|",
    "bold", "italic", "underline", "strikethrough", "|",
    "ul", "ol", "|",
    "font", "fontsize", "brush", "|",
    "align", "|",
    "link", "image", "table", "|",
    "undo", "redo", "|",
    "hr", "eraser", "copyformat", "|",
    "paragraph", "lineHeight",
  ],
  buttonsMD: ["bold", "italic", "underline", "ul", "ol", "link", "image"],
  buttonsSM: ["bold", "italic", "ul", "link"],
  pasteFromWordRemoveFontStyles: true,
  pasteFromWordRemoveStyles: true,
  uploader: { insertImageAsBase64URI: true },
  style: { fontFamily: "system-ui, -apple-system, sans-serif", fontSize: "16px", lineHeight: 1.6 },
};

function stripHtml(html: string): string {
  if (!html) return "";
  return html.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
}

const VALID_TAGS = ["NEW_ARRIVAL", "TRENDING", "BEST_SELLER"] as const;
type ValidTag = typeof VALID_TAGS[number];

function normalizeTag(val: unknown): ProductFeatureTag {
  if (!val) return null;
  const up = String(val).toUpperCase() as ValidTag;
  return VALID_TAGS.includes(up) ? up : null;
}

function CheckboxRow({ label, checked, onChange, description }: {
  label: string; checked: boolean; onChange: (v: boolean) => void; description?: string;
}) {
  return (
    <label className="flex items-start gap-3 cursor-pointer group">
      <input
        type="checkbox"
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
        className="mt-0.5 h-4 w-4 rounded border-border accent-primary cursor-pointer"
      />
      <div>
        <span className="text-sm font-medium group-hover:text-primary transition-colors">{label}</span>
        {description && <p className="text-xs text-muted-foreground mt-0.5">{description}</p>}
      </div>
    </label>
  );
}

function getInitialFormState(product: Product) {
  const tag = normalizeTag(product.featureTag);
  const auto = product.seoAutoGenerated ?? {};
  return {
    name: product.name,
    description: product.description || "",
    categoryIds: product.categories?.map((c) => c.id) ?? [],
    subCategoryIds: product.subCategories?.map((s) => s.id) ?? [],
    existingImages: product.images || [],
    featureTag: tag,
    isNewArrival: tag === "NEW_ARRIVAL" ? true : (product.isNewArrival ?? false),
    isFeatured: tag === "BEST_SELLER" ? true : (product.isFeatured ?? false),
    isHighDemand: tag === "TRENDING" ? true : (product.isHighDemand ?? false),
    showOnHome: product.showOnHome ?? false,
    isActive: product.isActive ?? true,
    metaTitle: product.metaTitle ?? product.name,
    metaDescription: product.metaDescription ?? stripHtml(product.description || "").slice(0, 160),
    metaKeywords:
      product.metaKeywords ??
      [product.name, ...(product.categories?.map((c) => c.name) ?? []), ...(product.subCategories?.map((s) => s.name) ?? [])]
        .filter(Boolean).join(", "),
    seoAuto: { metaTitle: !!auto.metaTitle, metaDescription: !!auto.metaDescription, metaKeywords: !!auto.metaKeywords },
  };
}

function ProductEditForm({ product, id }: { product: Product; id: string }) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const initial = getInitialFormState(product);

  const [name, setName] = useState(initial.name);
  const [description, setDescription] = useState(initial.description);
  const [categoryIds, setCategoryIds] = useState<string[]>(initial.categoryIds);
  const [subCategoryIds, setSubCategoryIds] = useState<string[]>(initial.subCategoryIds);
  const [existingImages, setExistingImages] = useState<ProductImage[]>(initial.existingImages);
  const [newImages, setNewImages] = useState<File[]>([]);
  const [featureTag, setFeatureTag] = useState<ProductFeatureTag>(initial.featureTag);
  const [isFeatured, setIsFeatured] = useState(initial.isFeatured);
  const [isNewArrival, setIsNewArrival] = useState(initial.isNewArrival);
  const [isHighDemand, setIsHighDemand] = useState(initial.isHighDemand);
  const [showOnHome, setShowOnHome] = useState(initial.showOnHome);
  const [isActive, setIsActive] = useState(initial.isActive);
  const [seoOpen, setSeoOpen] = useState(false);
  const [metaTitle, setMetaTitle] = useState(initial.metaTitle);
  const [metaDescription, setMetaDescription] = useState(initial.metaDescription);
  const [metaKeywords, setMetaKeywords] = useState(initial.metaKeywords);
  const [seoAuto, setSeoAuto] = useState(initial.seoAuto);

  const { data: categories = [] } = useQuery({
    queryKey: ["categories"],
    queryFn: () => categoriesApi.getAll(),
  });

  const { data: subCategories = [] } = useQuery({
    queryKey: ["subcategories", categoryIds],
    queryFn: () => subCategoriesApi.getByCategories(categoryIds),
    enabled: categoryIds.length > 0,
  });

  const handleFeatureTagChange = (v: string) => {
    const tag = v === "__none__" ? null : (v as ProductFeatureTag);
    setFeatureTag(tag);
    setIsNewArrival(tag === "NEW_ARRIVAL");
    setIsFeatured(tag === "BEST_SELLER");
    setIsHighDemand(tag === "TRENDING");
  };

  const removeImageMutation = useMutation({
    mutationFn: (imageId: string) => productsApi.deleteImage(id!, imageId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["product", id] });
      queryClient.invalidateQueries({ queryKey: ["products"] });
      toast.success("Image removed");
    },
    onError: (e) => toast.error(getApiError(e)),
  });

  const removeExistingImage = (img: ProductImage) => {
    if (!img.id) return;
    removeImageMutation.mutate(img.id, {
      onSuccess: () => setExistingImages((prev) => prev.filter((i) => i.id !== img.id)),
    });
  };

  const handleCategoryToggle = (catId: string) => {
    setCategoryIds((prev) => prev.includes(catId) ? prev.filter((c) => c !== catId) : [...prev, catId]);
    setSubCategoryIds((prev) =>
      prev.filter((sid) => { const sub = subCategories.find((s) => s.id === sid); return !sub || sub.categoryId !== catId; })
    );
  };

  const handleSubCategoryToggle = (subId: string) => {
    setSubCategoryIds((prev) => prev.includes(subId) ? prev.filter((s) => s !== subId) : [...prev, subId]);
  };

  const updateMutation = useMutation({
    mutationFn: () =>
      productsApi.update(
        id!,
        {
          name: name.trim(),
          description: description || "",
          categoryIds,
          subCategoryIds,
          featureTag,
          isFeatured,
          isNewArrival,
          isHighDemand,
          showOnHome,
          isActive,
          metaTitle: metaTitle.trim() || "",
          metaDescription: metaDescription.trim() || "",
          metaKeywords: metaKeywords.trim() || "",
          images: existingImages.map((img, idx) => ({ id: img.id, url: img.url, position: idx })),
        },
        newImages.length ? newImages : undefined
      ),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["product", id] });
      queryClient.invalidateQueries({ queryKey: ["products"] });
      toast.success("Product updated");
      navigate("/products");
    },
    onError: (e) => toast.error(getApiError(e)),
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) { toast.error("Name is required"); return; }
    if (!categoryIds.length) { toast.error("Select at least one category"); return; }
    updateMutation.mutate();
  };

  return (
    <div className="max-w-3xl space-y-6">
      <form onSubmit={handleSubmit} className="space-y-6 border border-border bg-card p-6 rounded-lg">
        {/* Name */}
        <div>
          <Label>Name *</Label>
          <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Product name" required className="mt-1 border-border" />
        </div>

        {/* Categories */}
        <div className="w-full">
          <Label>Categories * (select at least one)</Label>
          <div className="mt-2 w-full border border-border rounded p-3 max-h-48 overflow-y-auto space-y-2">
            {categories.length === 0
              ? <p className="text-sm text-muted-foreground">No categories found.</p>
              : categories.map((c) => (
                <label key={c.id} className="flex items-center gap-2 cursor-pointer">
                  <input type="checkbox" checked={categoryIds.includes(c.id)} onChange={() => handleCategoryToggle(c.id)} className="rounded border-border h-4 w-4" />
                  <span className="text-sm">{c.name}</span>
                </label>
              ))
            }
          </div>
        </div>

        {/* SubCategories */}
        <div className="w-full">
          <Label>SubCategories (optional)</Label>
          <div className="mt-2 w-full border border-border rounded p-3 max-h-48 overflow-y-auto space-y-2">
            {categoryIds.length === 0
              ? <p className="text-sm text-muted-foreground">Select a category first.</p>
              : subCategories.length === 0
                ? <p className="text-sm text-muted-foreground">No subcategories for selected categories.</p>
                : subCategories.map((s) => (
                  <label key={s.id} className="flex items-center gap-2 cursor-pointer">
                    <input type="checkbox" checked={subCategoryIds.includes(s.id)} onChange={() => handleSubCategoryToggle(s.id)} className="rounded border-border h-4 w-4" />
                    <span className="text-sm">{s.name}</span>
                  </label>
                ))
            }
          </div>
        </div>

        {/* Feature Tag */}
        <div>
          <Label>Feature tag (home sections)</Label>
          <p className="text-xs text-muted-foreground mb-2">Choosing a tag will auto-set the related flags below.</p>
          <Select value={featureTag ?? "__none__"} onValueChange={handleFeatureTagChange}>
            <SelectTrigger className="mt-1 border-border w-full max-w-xs">
              <SelectValue placeholder="None" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="__none__">None</SelectItem>
              <SelectItem value="NEW_ARRIVAL">New Arrival</SelectItem>
              <SelectItem value="TRENDING">Trending (High Demand)</SelectItem>
              <SelectItem value="BEST_SELLER">Best Seller (Featured)</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Boolean flags */}
        <div className="border border-border rounded p-4 space-y-3 bg-muted/20">
          <p className="text-sm font-medium mb-1">Product flags</p>
          <CheckboxRow
            label="New Arrival"
            checked={isNewArrival}
            onChange={(v) => { setIsNewArrival(v); if (v) { setFeatureTag("NEW_ARRIVAL"); setIsFeatured(false); setIsHighDemand(false); } else if (featureTag === "NEW_ARRIVAL") setFeatureTag(null); }}
            description="Shows in New Arrivals section on home page"
          />
          <CheckboxRow
            label="High Demand / Trending"
            checked={isHighDemand}
            onChange={(v) => { setIsHighDemand(v); if (v) { setFeatureTag("TRENDING"); setIsFeatured(false); setIsNewArrival(false); } else if (featureTag === "TRENDING") setFeatureTag(null); }}
            description="Shows in High Demand section on home page"
          />
          <CheckboxRow
            label="Featured / Best Seller"
            checked={isFeatured}
            onChange={(v) => { setIsFeatured(v); if (v) { setFeatureTag("BEST_SELLER"); setIsNewArrival(false); setIsHighDemand(false); } else if (featureTag === "BEST_SELLER") setFeatureTag(null); }}
            description="Shows in Featured Products section on home page"
          />
          <CheckboxRow
            label="Show on Home"
            checked={showOnHome}
            onChange={setShowOnHome}
            description="Pinned to home page listing"
          />
          <CheckboxRow
            label="Active"
            checked={isActive}
            onChange={setIsActive}
            description="Inactive products are hidden from the website"
          />
        </div>

        {/* Description */}
        <div>
          <Label>Description</Label>
          <div className="mt-1 w-full border border-border overflow-hidden rounded">
            <JoditEditor
              value={description}
              onChange={(v) => setDescription(v)}
              onBlur={(v) => setDescription(v)}
              config={JODIT_CONFIG}
            />
          </div>
        </div>

        {/* SEO */}
        <div className="border border-border rounded">
          <button
            type="button"
            onClick={() => setSeoOpen((o) => !o)}
            className="w-full flex items-center justify-between p-4 text-left hover:bg-muted/50 transition-colors"
          >
            <span className="font-medium text-sm">SEO Settings</span>
            {seoOpen ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
          </button>
          {seoOpen && (
            <div className="border-t border-border p-4 space-y-4 bg-muted/20">
              <p className="text-xs text-muted-foreground">Leave empty to auto-generate from product name & description.</p>
              <div className="space-y-3">
                <div>
                  <Label className="flex items-center gap-2 text-sm">
                    Meta Title {seoAuto.metaTitle && <span className="text-xs font-normal text-muted-foreground">(Auto)</span>}
                  </Label>
                  <Input value={metaTitle} onChange={(e) => { setMetaTitle(e.target.value); setSeoAuto((a) => ({ ...a, metaTitle: false })); }} placeholder="Auto from product name" className="mt-1 border-border" />
                </div>
                <div>
                  <Label className="flex items-center gap-2 text-sm">
                    Meta Description {seoAuto.metaDescription && <span className="text-xs font-normal text-muted-foreground">(Auto)</span>}
                  </Label>
                  <Input value={metaDescription} onChange={(e) => { setMetaDescription(e.target.value); setSeoAuto((a) => ({ ...a, metaDescription: false })); }} placeholder="Auto from description" className="mt-1 border-border" />
                </div>
                <div>
                  <Label className="flex items-center gap-2 text-sm">
                    Meta Keywords {seoAuto.metaKeywords && <span className="text-xs font-normal text-muted-foreground">(Auto)</span>}
                  </Label>
                  <Input value={metaKeywords} onChange={(e) => { setMetaKeywords(e.target.value); setSeoAuto((a) => ({ ...a, metaKeywords: false })); }} placeholder="Auto from name + categories" className="mt-1 border-border" />
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Existing images */}
        <div>
          <Label>Existing images</Label>
          <p className="text-xs text-muted-foreground mb-2">Click Remove to permanently delete an image from storage and database.</p>
          {existingImages.length === 0
            ? <p className="text-sm text-muted-foreground">No images.</p>
            : (
              <div className="flex flex-wrap gap-3 mt-2">
                {existingImages.map((img, idx) => (
                  <div key={img.id} className="border border-border rounded overflow-hidden">
                    <img src={img.url} alt="" className="w-28 h-28 object-cover block" />
                    <div className="bg-muted/30 px-1 py-0.5 text-center text-xs text-muted-foreground">#{idx + 1}</div>
                    <Button type="button" variant="destructive" size="sm" className="w-full rounded-none" onClick={() => removeExistingImage(img)} disabled={removeImageMutation.isPending}>
                      Remove
                    </Button>
                  </div>
                ))}
              </div>
            )
          }
        </div>

        {/* New images */}
        <div>
          <Label>Upload new images (max {Math.max(0, 4 - existingImages.length)} more)</Label>
          <ImageUploadZone value={newImages} onChange={setNewImages} max={Math.max(0, 4 - existingImages.length)} className="mt-2" disabled={existingImages.length >= 4} />
        </div>

        {/* Actions */}
        <div className="flex gap-3 pt-2">
          <Button type="button" variant="outline" onClick={() => navigate("/products")}>Cancel</Button>
          <Button type="submit" disabled={updateMutation.isPending || !categoryIds.length} className="min-w-[100px]">
            {updateMutation.isPending ? "Saving..." : "Update Product"}
          </Button>
        </div>
      </form>
    </div>
  );
}

export function ProductEdit() {
  const { id } = useParams<{ id: string }>();
  const { data: product, isLoading, isError, error, refetch } = useQuery({
    queryKey: ["product", id],
    queryFn: () => productsApi.getById(id!),
    enabled: !!id,
  });

  if (!id) return <p className="text-muted-foreground">Product ID missing.</p>;

  if (isError) {
    return (
      <div className="space-y-3 max-w-3xl">
        <p className="text-destructive font-medium">Failed to load product.</p>
        <p className="text-sm text-muted-foreground">{error instanceof Error ? error.message : "Check connection."}</p>
        <Button type="button" variant="outline" onClick={() => refetch()}>Retry</Button>
      </div>
    );
  }

  if (isLoading || !product) {
    return (
      <div className="space-y-4 max-w-3xl">
        <div className="h-10 bg-muted animate-pulse w-64 rounded" />
        <div className="h-64 bg-muted animate-pulse w-full rounded" />
      </div>
    );
  }

  return <ProductEditForm key={product.id} product={product} id={id} />;
}
